workflows:
  Well Testing:
    name: Well Testing
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Verify project location
        script: |
          echo "PWD=$(pwd)"
          ls -la
          test -f pubspec.yaml || (echo "pubspec.yaml not found" && exit 1)

      # If this repo was created without the ios folder, generate it
      - name: Ensure iOS platform exists
        script: |
          if [ ! -d ios ]; then
            flutter create .
          fi

      - name: Flutter pub get
        script: |
          flutter pub get

      # Optional: set iOS deployment target to 12.0+ to satisfy plugins like sqflite/path_provider
      - name: Set iOS deployment target (optional but recommended)
        script: |
          /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 12.0" ios/Flutter/AppFrameworkInfo.plist || true
          if [ -f ios/Podfile ]; then
            sed -i '' 's/platform :ios, .*/platform :ios, "12.0"/' ios/Podfile || true
          fi

      - name: Build iOS (simulator)
        script: |
          flutter build ios --simulator --debug

    artifacts:
      - build/ios/iphonesimulator/*.app
